---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
platforms:
  - name: docker
    hostname: docker
    box: opensuse/Leap-15.4.x86_64
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
